services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - /home/node/db

  database:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: overcooked
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: overcooked
      MYSQL_PASSWORD: overcooked
    volumes:
      - /home/node/app